apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"monitoring.coreos.com/v1","kind":"PrometheusRule","metadata":{"annotations":{},"labels":{"release":"monitoring"},"name":"app-alerts","namespace":"monitoring"},"spec":{"groups":[{"name":"apps.rules","rules":[{"alert":"PodCrashLooping","annotations":{"description":"Le pod {{ $labels.pod }} redémarre en boucle.","summary":"Pod en CrashLoopBackOff détecté dans le namespace apps"},"expr":"rate(kube_pod_container_status_restarts_total{namespace=\"apps\"}[5m]) * 60 \u003e 0","for":"30s","labels":{"severity":"critical"}}]}]}}
  creationTimestamp: "2026-09-17T21:07:37Z"
  generation: 1
  labels:
    release: monitoring
  name: app-alerts
  namespace: monitoring
  resourceVersion: "15891"
  uid: 0e91e130-9610-4bc9-a86c-1679d6bbd523
spec:
  groups:
  - name: apps.rules
    rules:
    - alert: PodCrashLooping
      annotations:
        description: Le pod {{ $labels.pod }} redémarre en boucle.
        summary: Pod en CrashLoopBackOff détecté dans le namespace apps
      expr: rate(kube_pod_container_status_restarts_total{namespace="apps"}[5m]) *
        60 > 0
      for: 30s
      labels:
        severity: critical
