apiVersion: v1
items:
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ResourceQuota","metadata":{"annotations":{},"name":"apps-quota","namespace":"apps"},"spec":{"hard":{"limits.cpu":"4","limits.memory":"4Gi","pods":"10","requests.cpu":"2","requests.memory":"2Gi","services":"5"}}}
    creationTimestamp: "2026-09-17T16:45:48Z"
    name: apps-quota
    namespace: apps
    resourceVersion: "17452"
    uid: 8d5cf1a3-d3da-4e50-bfe6-94e35d508b0c
  spec:
    hard:
      limits.cpu: "4"
      limits.memory: 6Gi
      pods: "10"
      requests.cpu: "2"
      requests.memory: 4Gi
      services: "5"
  status:
    hard:
      limits.cpu: "4"
      limits.memory: 6Gi
      pods: "10"
      requests.cpu: "2"
      requests.memory: 4Gi
      services: "5"
    used:
      limits.cpu: 1200m
      limits.memory: 1792Mi
      pods: "4"
      requests.cpu: 600m
      requests.memory: 1408Mi
      services: "2"
kind: List
metadata:
  resourceVersion: ""
